sudo: required
dist: trusty
language: node_js
node_js:
    - "8"

matrix:
  fast_finish: true

cache:
    directories:
    - node_modules
    - "$HOME/.cache"

before_install:
    # install yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
    - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - yarn

script:
    - yarn lint
    - yarn build
    - yarn lib
    - yarn test

branches:
    only:
    - master
    - test
    - release
